### ISSUE TITLE
Bump major or minor number

### ISSUE THREAD

**Issue by KonstantinKlepikov** [twisted/incremental#77]
Have we any way to bump major/minor number incremental? I dont find solution in `incremental.update` - only last number.

**Comment by twm** [comment]
Incremental doesn't have major/minor numbers in the style of SemVer. It implements [CalVer](https://calver.org/) in the style used by Twisted projects: YY.MM.MICRO. The YY and MM components are sourced from the current date (this is because [backwards compatibility in Twisted is time-based](https://docs.twisted.org/en/stable/development/compatibility-policy.html)).

If you want to control the major/minor version explicitly then [`hatch version`](https://hatch.pypa.io/latest/version/) is one possible tool.

**Comment by twm** [comment]
Actually, I think this merits a documentation fix.

**Comment by twm** [comment]
Also, `python -m incremental.version --newversion 1.2.3` lets you set the version to whatever you like.

**Comment by twm** [comment]
I believe this was addressed in #112, which updates Incremental's docs to front CalVer.
